[versions]
# Project versions
nativeBuildTools = "0.9.12-SNAPSHOT"

# External dependencies
spock = "2.0-groovy-3.0"
maven = "3.3.9"
mavenAnnotations = "3.5.1"
mavenEmbedder = "3.8.1"
mavenWagon = "3.4.3"
graalvm = "21.1.0"
jackson = "2.12.4"
junitPlatform = "1.8.1"
junitJupiter = "5.8.1"
aether = "1.1.0"
slf4j = "1.7.9"
groovy = "3.0.8"
jgit = "5.12.0.202106070339-r"
jetty = "11.0.9"

[libraries]
# Local projects
nativeGradlePlugin = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "nativeBuildTools" }
nativeMavenPlugin = { module = "org.graalvm.buildtools:native-maven-plugin", version.ref = "nativeBuildTools" }
junitPlatformNative = { module = "org.graalvm.buildtools:junit-platform-native", version.ref = "nativeBuildTools" }
utils = { module = "org.graalvm.buildtools:utils", version.ref = "nativeBuildTools" }
jvmReachabilityMetadata = { module = "org.graalvm.buildtools:jvm-reachability-metadata", version.ref = "nativeBuildTools" }

# External dependencies
test-junit-platform-console = { module = "org.junit.platform:junit-platform-console", version.ref = "junitPlatform" }
test-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
test-junit-bom = { module = "org.junit:junit-bom", version.ref = "junitJupiter" }
test-junit-jupiter-core = { module = "org.junit.jupiter:junit-jupiter", version = "" }
test-junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "" }
test-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "" }
test-junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version = "" }
test-spock = { module = "org.spockframework:spock-core", version.ref = "spock" }

graalvm-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graalvm" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

maven-pluginApi = { module = "org.apache.maven:maven-plugin-api", version.ref = "maven" }
maven-pluginAnnotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version.ref = "mavenAnnotations" }
maven-core = { module = "org.apache.maven:maven-core", version.ref = "maven" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version.ref = "maven" }
maven-compat = { module = "org.apache.maven:maven-compat", version.ref = "maven" }
maven-embedder = { module = "org.apache.maven:maven-embedder", version.ref = "mavenEmbedder" }
maven-aether-connector = { module = "org.eclipse.aether:aether-connector-basic", version.ref = "aether" }
maven-aether-wagon = { module = "org.eclipse.aether:aether-transport-wagon", version.ref = "aether" }
maven-wagon-file = { module = "org.apache.maven.wagon:wagon-file", version.ref = "mavenWagon" }
maven-wagon-http = { module = "org.apache.maven.wagon:wagon-http", version.ref = "mavenWagon" }
maven-wagon-provider = { module = "org.apache.maven.wagon:wagon-provider-api", version.ref = "mavenWagon" }

slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "jgit" }
jsch = { module = "org.eclipse.jgit:org.eclipse.jgit.ssh.jsch", version.ref="jgit" }

jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
