[versions]
# Project versions
nativeBuildTools = "0.11.4-SNAPSHOT"
metadataRepository = "0.3.33"

# External dependencies
spock = "2.1-groovy-3.0"
maven = "3.9.9"
mavenAnnotations = "3.6.4"
mavenEmbedder = "3.9.9"
mavenResolver = "1.9.22"
graalvm = "23.0.2"
openjson = "1.0.13"
junitPlatform = "1.13.0"
junitJupiter = "5.13.0"
slf4j = "1.7.9"
groovy = "3.0.11"
jetty = "11.0.11"
plexusUtils = "4.0.2"
plexusXml = "4.0.2"
cyclonedxMaven = "2.9.1"
pluginExecutorMaven = "2.4.1"

[libraries]
# Local projects
nativeGradlePlugin = { module = "org.graalvm.buildtools:native-gradle-plugin", version.ref = "nativeBuildTools" }
nativeMavenPlugin = { module = "org.graalvm.buildtools:native-maven-plugin", version.ref = "nativeBuildTools" }
junitPlatformNative = { module = "org.graalvm.buildtools:junit-platform-native", version.ref = "nativeBuildTools" }
utils = { module = "org.graalvm.buildtools:utils", version.ref = "nativeBuildTools" }
jvmReachabilityMetadata = { module = "org.graalvm.buildtools:graalvm-reachability-metadata", version.ref = "nativeBuildTools" }

# External dependencies
test-junit-platform-console = { module = "org.junit.platform:junit-platform-console", version.ref = "junitPlatform" }
test-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
test-junit-bom = { module = "org.junit:junit-bom", version.ref = "junitJupiter" }
test-junit-jupiter-core = { module = "org.junit.jupiter:junit-jupiter", version = "" }
test-junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version = "" }
test-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "" }
test-junit-vintage = { module = "org.junit.vintage:junit-vintage-engine", version = "" }
test-spock = { module = "org.spockframework:spock-core", version.ref = "spock" }

graalvm-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graalvm" }

openjson = { module = "com.github.openjson:openjson", version.ref = "openjson" }

maven-pluginApi = { module = "org.apache.maven:maven-plugin-api", version.ref = "maven" }
maven-pluginAnnotations = { module = "org.apache.maven.plugin-tools:maven-plugin-annotations", version.ref = "mavenAnnotations" }
maven-core = { module = "org.apache.maven:maven-core", version.ref = "maven" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version.ref = "maven" }
maven-compat = { module = "org.apache.maven:maven-compat", version.ref = "maven" }
maven-embedder = { module = "org.apache.maven:maven-embedder", version.ref = "mavenEmbedder" }
maven-resolver-basic = { module = "org.apache.maven.resolver:maven-resolver-connector-basic", version.ref = "mavenResolver"}
maven-resolver-transport-http = { module = "org.apache.maven.resolver:maven-resolver-transport-http", version.ref = "mavenResolver"}
maven-resolver-transport-file = { module = "org.apache.maven.resolver:maven-resolver-transport-file", version.ref = "mavenResolver"}

slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }

plexus-utils = { module = "org.codehaus.plexus:plexus-utils", version.ref = "plexusUtils" }

plexus-xml = { module = "org.codehaus.plexus:plexus-xml", version.ref = "plexusXml" }

cyclonedx-maven-plugin = { module = "org.cyclonedx:cyclonedx-maven-plugin", version.ref="cyclonedxMaven" }
plugin-executor-maven = { module = "org.twdata.maven:mojo-executor", version.ref="pluginExecutorMaven" }
