name: "Test junit-platform-native"

on:
  push:
    paths:
      - 'common/junit-platform-native/**'
      - '.github/actions/prepare-environment'
      - '.github/workflows/test-junit-platform-native.yml'
  pull_request:
    paths:
      - 'common/junit-platform-native/**'
      - '.github/actions/prepare-environment'
      - '.github/workflows/test-junit-platform-native.yml'
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'graalvm/native-build-tools' }}

jobs:
  test-junit-platform-native:
    name: "Test junit-platform-native"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 17 ]
        os: [ ubuntu-20.04 ]
    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v3
      - name: "ğŸ”§ Prepare environment"
        uses: ./.github/actions/prepare-environment
        with:
          java-version: ${{ matrix.java-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "â“ Checkstyle"
        run: ./gradlew :junit-platform-native:checkstyleMain :junit-platform-native:checkstyleTest
      - name: "â“ Hotspot test"
        run: ./gradlew :junit-platform-native:test
      - name: "â“ Native test"
        run: ./gradlew :junit-platform-native:nativeTest
      - name: "ğŸ“œ Upload tests results"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: tests-results
          path: common/junit-platform-native/build/reports/tests/
